# baseline-scan.ps1
# Phase 0.1 - Baseline scanner (ASCII-only): scan thuc te cua Agent Framework,
# sinh baseline.json + SYSTEM_STATISTICS.md + catalogs vao .opencode/baseline/.
# PS 5.1 friendly - khong dung ConvertFrom-Yaml. Giu UTF-8 no-BOM, ASCII source.

param(
  [switch]$Silent
)

$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$base = Join-Path $root '.opencode'
$bl   = Join-Path $base 'baseline'

if (-not (Test-Path $bl)) { New-Item -ItemType Directory -Path $bl -Force | Out-Null }

function Write-NoBom {
  param([string]$Path, [string]$Content)
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

# ---------- Counts ----------
$agents       = @(Get-ChildItem (Join-Path $base 'agents') -Filter *.md -ErrorAction SilentlyContinue).Count
$commands     = @(Get-ChildItem (Join-Path $base 'commands') -Filter *.md -ErrorAction SilentlyContinue).Count
$skillsReg    = @(Select-String -Path (Join-Path $base 'registry\skill-registry.yaml') -Pattern '^\s*- id: ' -ErrorAction SilentlyContinue).Count
$skillsDisk   = @(Get-ChildItem (Join-Path $base 'skills') -Directory -ErrorAction SilentlyContinue | Where-Object { $_.Name -ne 'knowledge' -and (Test-Path (Join-Path $_.FullName 'SKILL.md')) }).Count
$skillsAll    = @(Get-ChildItem (Join-Path $base 'skills') -Recurse -Filter SKILL.md -ErrorAction SilentlyContinue).Count
$knowledgeMd  = @(Get-ChildItem (Join-Path $base 'knowledge') -Recurse -Filter *.md -ErrorAction SilentlyContinue).Count
$knowledgeJson= @(Get-ChildItem (Join-Path $base 'knowledge') -Recurse -Filter *.json -ErrorAction SilentlyContinue).Count
$memory       = @(Get-ChildItem (Join-Path $base 'memory') -Recurse -File -ErrorAction SilentlyContinue).Count
$workflows    = @(Get-ChildItem (Join-Path $base 'workflow\definitions') -Filter *.yaml -ErrorAction SilentlyContinue).Count
$contracts    = @(Get-ChildItem $base -Recurse -Filter *.schema.yaml -ErrorAction SilentlyContinue).Count
$scripts      = @(Get-ChildItem (Join-Path $base 'scripts') -Filter *.ps1 -ErrorAction SilentlyContinue).Count
$registryFiles= @(Get-ChildItem (Join-Path $base 'registry') -File -ErrorAction SilentlyContinue).Count
$workflowEngine= @(Get-ChildItem (Join-Path $base 'workflow-engine') -Recurse -File -ErrorAction SilentlyContinue).Count

# Git info
$gitCommit = 'unknown'
try { $gitCommit = (& git rev-parse --short HEAD 2>$null).Trim() } catch { $gitCommit = 'unknown' }
$gitTag = 'untagged'
try { $gitTag = (& git describe --tags --abbrev=0 2>$null).Trim() } catch { $gitTag = 'untagged' }
$buildDate = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

# ---------- baseline.json ----------
$baseline = [ordered]@{
  version           = '3.0'
  framework         = 'v3'
  build_date        = $buildDate
  git_commit        = $gitCommit
  git_tag           = $gitTag
  repository        = 'https://github.com/mrdanhdanh/AIAgent.git'
  agents            = $agents
  commands          = $commands
  skills_registry   = $skillsReg
  skills_distinct   = $skillsDisk
  skills_all        = $skillsAll
  knowledge_md      = $knowledgeMd
  knowledge_json    = $knowledgeJson
  knowledge         = ($knowledgeMd + $knowledgeJson)
  memory            = $memory
  workflows         = $workflows
  contracts         = $contracts
  scripts           = $scripts
  registry_files    = $registryFiles
  workflow_engine   = $workflowEngine
}
$json = $baseline | ConvertTo-Json
Write-NoBom -Path (Join-Path $bl 'baseline.json') -Content $json

# ---------- SYSTEM_STATISTICS.md ----------
$statLines = @(
  '# SYSTEM_STATISTICS.md - Agent Framework Baseline'
  ''
  "> Generated by baseline-scan.ps1 - $buildDate"
  ''
  '## Entity Counts'
  ''
  '| Entity | Count | Note |'
  '|--------|-------|------|'
  "| Agents | $agents | .opencode/agents/*.md |"
  "| Commands | $commands | .opencode/commands/*.md |"
  "| Skills (registry) | $skillsReg | Capability Registry set |"
  "| Skills (distinct) | $skillsDisk | skills/ tru knowledge/ |"
  "| Skills (all SKILL.md) | $skillsAll | ke ca knowledge/* nested |"
  "| Knowledge (md) | $knowledgeMd | .opencode/knowledge/**/*.md |"
  "| Knowledge (json) | $knowledgeJson | index files |"
  "| Knowledge (total) | $(($knowledgeMd + $knowledgeJson)) | md + json |"
  "| Memory | $memory | .opencode/memory/** |"
  "| Workflows | $workflows | definitions/*.workflow.yaml |"
  "| Contracts (schema) | $contracts | *.schema.yaml |"
  "| Scripts | $scripts | *.ps1 |"
  "| Registry files | $registryFiles | .opencode/registry/ |"
  "| Workflow engine files | $workflowEngine | .opencode/workflow-engine/ |"
  ''
  '## Version & Baseline'
  ''
  '| Field | Value |'
  '|-------|-------|'
  "| Framework | v3 (baseline) |"
  "| Build date | $buildDate |"
  "| Git commit | $gitCommit |"
  "| Git tag | $gitTag |"
  ''
  '## Time comparison'
  ''
  'Doctor/Evolution read baseline.json de so sanh, khong can parse lai project.'
)
Write-NoBom -Path (Join-Path $bl 'SYSTEM_STATISTICS.md') -Content ($statLines -join "`n")

if (-not $Silent) {
  ''
  '=== baseline-scan ==='
  "agents=$assets agents_stdout=$agents commands=$commands skills_registry=$skillsReg skills_all=$skillsAll knowledge=$(($knowledgeMd+$knowledgeJson)) memory=$memory workflows=$workflows contracts=$contracts scripts=$scripts"
  "baseline.json + SYSTEM_STATISTICS.md -> $bl"
}