# catalog-builder.ps1
# Phase 0.1 - Build AGENT/COMMAND/SKILL/WORKFLOW/CONTRACT catalogs into .opencode/baseline/.
# Reads registry yaml (id/supports/purpose) via simple parser, outputs markdown catalogs.
# ASCII-only source (PS 5.1 reads .ps1 as ANSI).

param(
  [switch]$Silent
)

$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$base = Join-Path $root '.opencode'
$reg  = Join-Path $base 'registry'
$bl   = Join-Path $base 'baseline'

function Write-NoBom {
  param([string]$Path, [string]$Content)
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

# ---- AGENT_CATALOG: read agent.md frontmatter with utf8 ----
function Get-AgentDesc([System.IO.FileInfo]$f){
  $lines = Get-Content $f.FullName -Encoding utf8
  $i = 0
  while ($i -lt $lines.Count) {
    $ln = $lines[$i]
    if ($ln -match '^description:\s*(.+)$') {
      $val = $Matches[1].Trim()
      $collect = @()
      if ($val -eq '>-' -or $val -eq '>-') {
        $i++
        while ($i -lt $lines.Count -and $lines[$i] -match '^\s+\S') {
          $collect += $lines[$i].Trim()
          $i++
        }
        if ($collect.Count) { return ($collect -join ' ') }
        break
      }
      return $val
    }
    $i++
  }
  return ''
}

# pull capability mapping from registry by parsing each dashboard lines
function Get-Capability([string]$file,[string]$id,[string]$field){
  $rows = Get-Content (Join-Path $reg $file) -Encoding utf8
  $capture=$false; foreach($ln in $rows){
    if($ln -match "^\s*- id:\s*$id\s*$"){ $capture=$true; continue }
    if($capture -and $ln -match "^\s*$field\s*:\s*\[(.*)\]"){ return $Matches[1] }
    if($capture -and $ln -match '^\S'){ break }
  }
  return ''
}

$acat = @(
  '# AGENT_CATALOG.md - Agent Framework v3'
  ''
  '> Generated by catalog-builder.ps1'
  ''
  '| Agent | Purpose | Capabilities |'
  '|-------|---------|--------------|'
)
foreach ($a in Get-ChildItem (Join-Path $base 'agents') -Filter *.md | Sort-Object Name) {
  $name = $a.BaseName
  $desc = (Get-AgentDesc $a) -replace '\|','/'
  $cap  = Get-Capability 'agent-registry.yaml' $name 'capabilities'
  $acat += "| $name | $(if($desc){$desc}else{'-'}) | $(if($cap){$cap}else{'-'}) |"
}
Write-NoBom -Path (Join-Path $bl 'AGENT_CATALOG.md') -Content ($acat -join "`n")

# ---------------- COMMAND_CATALOG ----------------
$cmdRows = @()
foreach ($c in Get-ChildItem (Join-Path $base 'commands') -Filter *.md | Sort-Object Name) {
  $desc = (Get-AgentDesc $c) -replace '\|','/'
  $cmdRows += "| $($c.BaseName) | $(if($desc){$desc}else{'-'}) |"
}
$cmdcat = @(
  '# COMMAND_CATALOG.md - Agent Framework v3'
  ''
  '> Generated by catalog-builder.ps1'
  ''
  '| Command | Purpose |'
  '|---------|---------|'
)
$cmdcat += $cmdRows
Write-NoBom -Path (Join-Path $bl 'COMMAND_CATALOG.md') -Content ($cmdcat -join "`n")

# ---------------- SKILL_CATALOG from skill-registry ----------------
$skillRows = @()
$sk = Get-Content (Join-Path $reg 'skill-registry.yaml') -ErrorAction SilentlyContinue
$cur = ''; $supp = ''; $prio = ''
foreach ($ln in $sk) {
  if ($ln -match '^\s*- id:\s*(\S+)') {
    if ($cur -and $supp) { $skillRows += "| $cur | $supp | $prio |" }
    $cur = $Matches[1]; $supp = ''; $prio = ''
    continue
  }
  if ($cur -and $ln -match '^\s*supports:\s*\[(.*)\]') { $supp = $Matches[1]; continue }
  if ($cur -and $ln -match '^\s*priority:\s*(\d+)') { $prio = $Matches[1]; continue }
}
if ($cur -and $supp) { $skillRows += "| $cur | $supp | $prio |" }
$skillcat = @(
  '# SKILL_CATALOG.md - Agent Framework v3'
  ''
  '> Generated by catalog-builder.ps1 (registry - source of truth)'
  ''
  '| Skill | Supports Capabilities | Priority |'
  '|-------|-----------------------|----------|'
)
$skillcat += $skillRows
Write-NoBom -Path (Join-Path $bl 'SKILL_CATALOG.md') -Content ($skillcat -join "`n")

# ---------------- WORKFLOW_CATALOG ----------------
$wfcat = @(
  '# WORKFLOW_CATALOG.md - Agent Framework v3'
  ''
  '> Generated by catalog-builder.ps1 (workflow-engine v4)'
  ''
  '| Workflow | Phases | Status |'
  '|----------|--------|--------|'
)
foreach ($w in Get-ChildItem (Join-Path $base 'workflow\definitions') -Filter *.yaml | Sort-Object Name) {
  $wfcat += "| $($w.BaseName) | defined | active |"
}
Write-NoBom -Path (Join-Path $bl 'WORKFLOW_CATALOG.md') -Content ($wfcat -join "`n")

# ---------------- CONTRACT_CATALOG ----------------
$ccat = @(
  '# CONTRACT_CATALOG.md - Agent Framework v3'
  ''
  '> Generated by catalog-builder.ps1'
  ''
  '| Contract | Type | Used By |'
  '|----------|------|---------|'
)
foreach ($c in Get-ChildItem $base -Recurse -Filter *.schema.yaml | Sort-Object FullName) {
  $rel = $c.FullName.Substring($root.Length+1).Replace('\','/')
  $ccat += "| $($c.Name) | schema | $rel |"
}
Write-NoBom -Path (Join-Path $bl 'CONTRACT_CATALOG.md') -Content ($ccat -join "`n")

if (-not $Silent) {
  '=== catalog-builder ==='
  "wrote AGENT_CATALOG, COMMAND_CATALOG, SKILL_CATALOG, WORKFLOW_CATALOG, CONTRACT_CATALOG to $bl"
}
